CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE devices (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  device_name VARCHAR(128) NOT NULL,
  owned_by INTEGER,
  FOREIGN KEY (owned_by) REFERENCES devices(id)
);
